Ruby中的异常处理
===============

#Ruby 异常

    begin  
    # -  
    rescue OneTypeOfException  
    # -  
    rescue AnotherTypeOfException  
    # -  
    else  
    # 其他异常
    ensure
    # 总是被执行
    end

从 begin 到 rescue 中的一切是受保护的。如果代码块执行期间发生了异常，控制会传到 rescue 和 end 之间的块。

对于 begin 块中的每个 rescue 子句，Ruby 把抛出的异常与每个参数进行轮流比较。如果 rescue 子句中命名的异常与当前抛出的异常类型相同，或者是该异常的父类，则匹配成功。

如果异常不匹配所有指定的错误类型，我们可以在所有的 rescue 子句后使用一个 else 子句。

#使用 retry 语句
您可以使用 rescue 块捕获异常，然后使用 retry 语句从开头开始执行 begin 块。

    begin
        # 这段代码抛出的异常将被下面的 rescue 子句捕获
    rescue
        # 这个块将捕获所有类型的异常
        retry  # 这将把控制移到 begin 的开头
    end

    begin
       file = open("/unexistant_file")
       if file
          puts "File opened successfully"
       end
    rescue
       fname = "existant_file"
       retry
    end
异常可以赋值给变量：

    rescue ArgumentError, TypeError => e
以下是处理流程：

    打开时发生异常。
    跳到 rescue。fname 被重新赋值。
    通过 retry 跳到 begin 的开头。
    这次文件成功打开。
    继续基本的过程。
注意：如果被重新命名的文件不存在，本势力代码会无限尝试。所以异常处理时，谨慎使用 retry。

#使用 raise 语句
您可以使用 raise 语句抛出异常。下面的方法在调用时抛出异常。它的第二个消息将被输出。


    raise 
    OR
    raise "Error Message" 
    OR
    raise ExceptionType, "Error Message"
    OR
    raise ExceptionType, "Error Message" condition

第一种形式简单地重新抛出当前异常（如果没有当前异常则抛出一个 RuntimeError）。这用在传入异常之前需要解释异常的异常处理程序中。

第二种形式创建一个新的 RuntimeError 异常，设置它的消息为给定的字符串。该异常之后抛出到调用堆栈。

第三种形式使用第一个参数创建一个异常，然后设置相关的消息为第二个参数。

第四种形式与第三种形式类似，您可以添加任何额外的条件语句（比如 unless）来抛出异常。

    begin  
    puts 'I am before the raise.'  
    raise 'An error has occurred.'  
    puts 'I am after the raise.'  
    rescue  
        puts 'I am rescued.'  
    end  
    puts 'I am after the begin block.'  

#使用 ensure 语句
有时候，无论是否抛出异常，您需要保证一些处理在代码块结束时完成。例如，您可能在进入时打开了一个文件，当您退出块时，您需要确保关闭文件。

ensure 子句做的就是这个。ensure 放在最后一个 rescue 子句后，并包含一个块终止时总是执行的代码块。**它与块是否正常退出、是否抛出并处理异常、是否因一个未捕获的异常而终止，这些都没关系，ensure 块始终都会运行**。

    begin 
       #.. 过程
       #.. 抛出异常
    rescue 
       #.. 处理错误 
    ensure 
       #.. 最后确保执行
       #.. 这总是会执行
    end

